class NameGenerator {

    private readonly AI_NAMES: string[] = [
        //Spanish
        "King Alfonso",
        "King Sancho",
        "Catherine of Aragon",
        "King Ferdinand",
        "Pedro the Cruel",
        "Ramiro I of Aragon",
        "El Cid Campeador",
        "Count Berengeur",
        "Gonzalo de Códoba",
        "King Charles VIII",
        "Ordono II of León",
        "King Ramiro of León",
        "Hernan Cortéz",
        "Álvarez de Toledo",
        "Queen Isabella",
        "Cardinal Jiménez",
        //Aztecs
        "Itzcoatl",
        "Montezuma",
        "Axayactl",
        "Tizoc",
        "Ahuitzotol",
        "Cuitlauac",
        "Cuauhtemoc",
        "Maxixca",
        "Acamapichtli",
        "Ahuitzotol",
        "Huitzilihuitl",
        "Chimalpopoca",
        //Mayans
        "Black Serpent",
        "Flint Sky God",
        "Bird Jaguar",
        "Lady Great Skull Zero",
        "King Stormy Sky",
        "Shield Jaguar II",
        "Curl Snout",
        "Eighteen Rabbit",
        "Smoke Imix God",
        "Great Jaguar Paw",
        "Smoking Squirrel",
        "Smoke Shell",
        "Smoke Monkey",
        "Smoking Frog",
        "Waterlily Jaguar",
        //Huns
        "Attila the Hun",
        "Bleda the Hun",
        "Mundzuk the Hun",
        "Ruga the Hun",
        "Uldin the Hun",
        "Balamber the Hun",
        "Ellak the Hun",
        "Dengizk the Hun",
        "Ernak the Hun",
        //Koreans
        "Kwanggaeto the Great",
        "General Ulji Mun-tok",
        "General Kyebaek",
        "General Kim Yu-shin",
        "Admiral Chang Bo-ko",
        "General Taejoyoung",
        "Wang Kon",
        "General Kang Kam-chan",
        "Ch'oe Mu-son",
        "General Ch'oe Young",
        "Yi Song-kye",
        "Sejong the Great",
        "General Kwon Yul",
        "Admiral Yi Sun-shin",
        //Italians
        "Pope Gregory VII",
        "Pietro Gradenigo",
        "Francesco I Sforza",
        "Ottone Visconti",
        "Domenico Selvo",
        "Castruccio Castracani",
        "Simone Boccanegra",
        "Maurizio Galbaio",
        "Alboin",
        "Liutprand the Lombard",
        "Arechis II of Benevento",
        "Gisulf I of Salerno",
        //Indians
        "Iltutmish",
        "Babur",
        "Humayun",
        "Akbar",
        "Bappa Rawal",
        "Man Singh I",
        "Sultan Ala-ud-din Khilji",
        "Sultan Balban",
        //Incas
        "Manco Inca Yupanqui",
        "Manco Cápac",
        "Túpac Inca Yupanqui",
        "Viracocha",
        "Pachacuti",
        "Huayna Cápac",
        "Huascár",
        "Tópa Huallpa",
        "Atahualpa",
        //Magyars
        "István I",
        "Fehér András",
        "Bajnok Béla",
        "László I",
        "Kálmán I",
        "Károly Róbert",
        "Nagy Lajos",
        "Matthias Corvinus",
        //Slavs
        "Wenceslaus I",
        "Ottokar I",
        "Rurik I",
        "Oleg the Seer",
        "Vladimir the Great",
        "Alexander Nevsky",
        "Yuri II",
        "Casimir II the Great",
        "Boleslaw the Brave",
        "Wenceslaus the One-Eyed",
        "Sviatoslav the Brave",
        "Yaroslav the Wise",
        //Portuguese
        "Joao I",
        "Henry the Navigator",
        "Afonso V",
        "Manuel I",
        "Afonso de Albuquerque",
        "Vasco da Gama",
        "Bartolomeu Dias",
        "Vimara Peres",
        "Pedro Alvares Cabral",
        "Duarte Pacheco Pereira",
        "Nuno Alvares Pereira",
        //Ethiopians
        "Kaleb of Axum",
        "Dil Na'od",
        "Lalibela",
        "Yakuno Amlak",
        "Amda Seyon",
        "Zara Yaqob",
        "Gelawdewos",
        "Frumentius",
        "Yared",
        "Yodit",
        "Amir Habbuba",
        "Abba Guba",
        //Malians
        "Sundjata",
        "Mansa Musa",
        "Ouali Keita",
        "Soumaoro Kante",
        "Souleyman Keita",
        "Mansa Mahmud IV",
        "Mamadou",
        "Tiramakhan",
        "Mansa Sakura",
        "Mari Djata I",
        "Abu Bakr II",
        "Soumaba Cisse",
        //Berbers
        "Yusuf",
        "Tariq ibn Ziyad",
        "Musa ibn Nusayr",
        "Kusayla",
        "Maysara",
        "Idris I",
        "Abu Yazid",
        "Abdallah ibn Yasin",
        "Abu Bakr ibn Umar",
        "Ibn Tumart",
        "Abd al-Mu'min",
        "Salih ibn Tarif",
        //Khmer
        "Suryavarman I",
        "Udayadityavarman I",
        "Jayaviravarman",
        "Sangrama",
        "Jayavarman II",
        "Yasovarman I",
        "Rajendravarman II",
        "Suryavarman II Paramavishnuloka",
        "Jayavarman VII Mahaparamasaugata",
        "Indravarman III",
        "Ponhea Yat",
        "Barom Reachea I",
        //Malay
        "Dharmasetu",
        "Samaratungga",
        "Balaputra",
        "Raden Wijaya",
        "Jayanegara",
        "Gajah Mada",
        "Hayam Wuruk",
        "Sang Nila Utama",
        "Parameswara",
        "Sultan Muzaffar Shah",
        "Sultan Mansur Shah",
        "Sultan Mahmud Shah",
        //Burmese
        "Bayinnaung",
        "Tabinshwehti",
        "Anawrahta",
        "Mingyi Nyo",
        "Nanda",
        "Kyansittha",
        "Sithu",
        "Swasawke",
        "Minkhaung",
        "Narapati",
        "Min Bin",
        "Binnya Dala",
        //Vietnamese
        "Ly Nam De",
        "Phung Hung",
        "Ngo Quyen",
        "Dinh Bo Linh",
        "Le Dai Hanh",
        "Ly Nhan Tong",
        "Ly Thai To",
        "Tran Thai Tong",
        "Tran Nhan Tong",
        "Tran Anh Tong",
        "Le Thai To",
        "Le Thanh Tong",
        //Britons
        "Henry V",
        "Richard II",
        "William III",
        "Lord Talbot",
        "Prince John",
        "King Edward",
        "Henry Tudor",
        "Earl of Wessex",
        "Earl of Warwick",
        "Alfred the Great",
        "Lord Henry Percy",
        "The Black Prince",
        "Duke of Normandy",
        "Edward Longshanks",
        "Henry Bolingbroke",
        "Richard the Lionhearted",
        //Franks
        "Roland",
        "Louis IX",
        "Louis VI",
        "Louis XI",
        "Charles VI",
        "Charlemagne",
        "King Philip I",
        "Charles Martel",
        "Pepin the Short",
        "Philip the Good",
        "Charles the Bold",
        "Philip II Augustus",
        "Constable Richemont",
        "Jean Dunois of Orleans",
        "Raymond, Prince of Antioch",
        //Goths
        "Athaulf",
        "King Wallia",
        "King Alaric II",
        "King Leovigild",
        "Teias the Goth",
        "General Theodemir",
        "Theodoric the Goth",
        "King Euric the Visigoth",
        //Teutons
        "King Karl",
        "Henry III",
        "Lothair II",
        "King Rupert",
        "Frederick II",
        "Emp. Lothair",
        "Maximilian II",
        "King Heinrich",
        "King Wenceslas",
        "Henry the Lion",
        "Otto the Great",
        "Emp. Leopold I",
        "Albert the Bear",
        "Conrad the Salian",
        "Rudolph of Swabia",
        "Frederick Barbarossa",
        "Maximilian of Hapsburg",
        //Japanese
        "Hojou Soun",
        "Saito Dousan",
        "Oda Nobunaga",
        "Gamou Ujisato",
        "Date Masamune",
        "Mouri Motonari",
        "Uesugi Kenshin",
        "Takeda Shingen",
        "Sanada Yukimura",
        "Tokugawa Ieyasu",
        "Nitta Yoshisada",
        "Tairano Kiyomori",
        "Ashikaga Takauji",
        "Imagawa Yoshimoto",
        "Kusunoki Masashige",
        "Hosokawa Katsumoto",
        "Minamotono Yoritomo",
        "Fujiwarano Michinaga",
        "Minamotono Yoshitsune",
        //Chinese
        "Zhu Di",
        "Yue Fei",
        "Zheng He",
        "Lin Chong",
        "Yang Jian",
        "Wu Ze-tian",
        "Li Shi-min",
        "Li zi-cheng",
        "Mu Gui-ying",
        "Zhao Kuang-yin",
        "Wen Tian-xiang",
        "Zhu Yuan-zhang",
        //Byzantines
        "Belisarius",
        "Emp. Leo VI",
        "Emp. Justinian",
        "Emp. Mauricius",
        "Emp. Michael V",
        "Emp. Anastasius",
        "Emp. Romanus II",
        "Emp. Alexius IV",
        "Emp. Constantine",
        "Emp. Tiberius III",
        "Heraclius the Elder",
        "Basil the Macedonian",
        "Michael the Stammerer",
        "General Manuel Comnenus",
        //Persians
        "Yakub",
        "Mondhir",
        "Shah Rukh",
        "King Bahram",
        "Shah Takash",
        "Emp. Kavadh",
        "Emp. Hormizd",
        "Mohammad Shah",
        "Emp. Yazdegird",
        "King Chosroes II",
        //Saracens
        "Saladin",
        "Baibars",
        "Kala'un",
        "Kerboga",
        "Nur-ed-din",
        "Al-Mu'tasim",
        "Atabeg Zangi",
        "Caliph Yazid",
        "General Khalid",
        "Caliph Abu Bekr",
        "General Shirkuh",
        //Turks
        "Orkhan",
        "Seljuk",
        "Bayazid",
        "Alp Arslan",
        "Kai Kobad",
        "Danishmend",
        "Chaghri Beg",
        "Sultan Murad",
        "Sultan Sanjar",
        "Sultan Malik-shah",
        "Ghiyas-ud-Din of Ghor",
        "General Togrul Beg",
        "Atsiz the Khwarezmian",
        "Suleiman the Magnificent",
        //Vikings
        "Sigurd",
        "Siegfried",
        "Canute IV",
        "Jarl Osbiorn",
        "Erik Bloodax",
        "Erik the Red",
        "King Godfred",
        "Chief Thorgest",
        "Olaf Haraldson",
        "Sweyn Forkbeard",
        "Magnus Olafsson",
        "Olaf Tryggvasson",
        "Harald Bluetooth",
        "Harald Hardraade",
        "Magnus the Strong",
        "Halfdan the Black",
        //Mongols
        "Kabul",
        "Chepe",
        "Subotai",
        "Uzbeg",
        "Kushluk",
        "Kitboga",
        "Batu Khan",
        "Tamerlane",
        "Guyuk Khan",
        "Mongke Khan",
        "Ogedei Khan",
        "Genghis Khan",
        "Khubilai Khan",
        "Toktamish Khan",
        //Celts
        "Aedan",
        "Brude",
        "Conall",
        "Ainmire",
        "Cunedda",
        "Vortigern",
        "Diarmait",
        "Maelgwn",
        "Macbeth",
        "Columba",
        "Ambrosius",
        "Aethelfrith",
        "Brian Boru",
        "William Wallace",
        "Robert the Bruce",
        "Athelred the Unready"
    ];

    private seed: number;

    private LCG = () => (2 ** 31 - 1 & (this.seed = Math.imul(48271, this.seed))) / 2 ** 31;

    constructor(seed: number = Date.now()) {
        if (seed === 0) {
            throw new Error('LCG must not be initialized with 0');
        }
        this.seed = seed;
    }

    public nextName(): string {
        return this.AI_NAMES[Math.floor(this.LCG() * this.AI_NAMES.length)];
    }

    public static getNameFromLocalStorage(defaultIfError: string | null = null): string | null {
        try {
            return localStorage.getItem('username');
        } catch (e) {
            return defaultIfError;
        }
    }

    public static writeNameToLocalStorage(name: string) {
        try {
            localStorage.setItem('username', name);
        } catch (e) {
            // ignore
        }
    }
}

export default NameGenerator;
