export enum Actions {
    SEND_MESSAGE = 'SEND_MESSAGE',
    CHANGE_OWN_NAME = 'CHANGE_OWN_NAME',
    SET_OWN_ROLE = 'SET_OWN_ROLE',
    SET_LANGUAGE = 'SET_LANGUAGE',
    SHOW_NAME_MODAL = 'SHOW_NAME_MODAL',
    SHOW_ROLE_MODAL = 'SHOW_ROLE_MODAL',
    SET_EDITOR_PRESET = 'SET_EDITOR_PRESET',
    SET_EDITOR_TURN = 'SET_EDITOR_TURN',
    SET_EDITOR_NAME = 'SET_EDITOR_NAME',
    SET_EDITOR_CIVILISATIONS = 'SET_EDITOR_CIVILISATIONS',
}

export enum ServerActions {
    APPLY_CONFIG = 'APPLY_CONFIG',
    CONNECT_PLAYER = 'CONNECT_PLAYER',
    SET_READY = 'SET_READY',
    ACTION_COMPLETED = 'ACTION_COMPLETED',
    SET_EVENTS = 'SET_EVENTS',
    COUNTDOWN = 'COUNTDOWN',
    REPLAY = 'REPLAY',

}

export enum ClientActions {
    CONNECT = 'CONNECT',
    SET_ROLE = 'SET_ROLE',
    SEND_READY = 'SEND_READY',
    CLICK_CIVILISATION = 'CLICK_CIVILISATION',
    DISCONNECT = 'DISCONNECT',
}
