export enum Actions {
    ACTION_COMPLETED = 'ACTION_COMPLETED',
    SEND_JOIN = 'SEND_JOIN',
    SEND_MESSAGE = 'SEND_MESSAGE',
    SET_NAME = 'SET_NAME',
    CHANGE_OWN_NAME = 'CHANGE_OWN_NAME',
    CLICK_CIVILISATION = 'CLICK_CIVILISATION',
    APPLY_CONFIG = 'APPLY_CONFIG',
    SET_LANGUAGE = 'SET_LANGUAGE'
}